name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Breaking change'
    labels:
      - 'Breaking Change'
  - title: 'Fixes'
    labels:
      - 'bug'
  - title: 'Refactor'
    labels:
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES